[project]
name = "duckdb-s3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow>=2.10.2",
    "boto3>=1.35.54",
    "duckdb>=1.1.2",
    "ipykernel>=6.29.5",
    "loguru>=0.7.2",
    "requests>=2.32.3",
]
